### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PetteriM1** [NukkitX/ProxyPass#1]
When trying to connect
[https://hastebin.com/oxirareqaz.md](https://hastebin.com/oxirareqaz.md)

Bedrock server 1.8.1.2
ProxyPass build master/#4

**Comment by SupremeMortal** [comment]
Is xbox auth disabled on your bedrock server and on the same LAN?

**Comment by PetteriM1** [comment]
> Is xbox auth disabled on your bedrock server and on the same LAN?

yes
