### ISSUE TITLE
Doesn't work on 1.18.31 & 1.18.30!

### ISSUE THREAD

**Issue by VinkyV** [NukkitX/ProxyPass#31]
Today i tested it and it doesn't working with my Minecraft bedrock 1.18.31.
Minecraft saying the server outdated! And the console says hundred of errors. Fix it please this software is very useful!

Tested 1.18.30 it doens't work too :(

![Снимок экрана (116)](https://user-images.githubusercontent.com/75137786/169581730-e73a505a-7904-432a-95f6-f1b36cfa5e0e.png)

**Comment by ApocalypsjeNL** [comment]
It looks like there is a version mismatch with the target server, what version is it running on?

**Comment by VinkyV** [comment]
> Похоже, что существует несоответствие версии с целевым сервером, на какой версии он работает?

Yes thanks i used the wrong version of Minecraft server!
