### ISSUE TITLE
Spammed with ArrayIndexOutOfBoundsException when reading PlayerAuthInputPacket

### ISSUE THREAD

**Issue by ambiennt** [NukkitX/ProxyPass#32]
![image](https://user-images.githubusercontent.com/63216972/178156935-c926685c-a2b5-4cf2-ae7b-4f9e28be84d8.png)

- The issue arose starting in 1.19.0/protocol v527
- Whether or not the server or client is on 1.19.0/1.19.2 makes no difference
- The console output basically becomes unreadable as a result of the spammed errors
- Testing on Bedrock Dedicated Server

**Comment by Kazzuk** [comment]
Resolved in CloudburstMC/Protocol#165
