### ISSUE TITLE
will you add proxy-protocol support?

### ISSUE THREAD

**Issue by lootoos** [NukkitX/ProxyPass#33]
in order to be able to get normal IP addresses to the minecraft server.
in order for the server to be able to receive external IP addresses of players.
by the way, nginx supports proxy_protocol (https://imgbb.com/FnpFhPk), will you introduce such functionality in ProxyPass?

**Comment by mantrakp04** [comment]
@lootoos did u manage to run bedrock server on nginx proxy protocol udp? I was able to run the server, however i am not able to forward the client ip, so i cant really find the use of proxy protocol.

**Comment by rtm516** [comment]
ProxyPass is for debugging and investigation of the bedrock protocol, not for proxy protocol and reverse proxies
