### ISSUE TITLE
Unable to connect to server, protocol 554

### ISSUE THREAD

**Issue by CoolLoong** [NukkitX/ProxyPass#37]

**Comment by CoolLoong** [comment]
[Artifacts](https://ci.opencollab.dev/job/NukkitX/job/ProxyPass/job/master/63/)

**Comment by CoolLoong** [comment]
I found that the reason for the failure to connect to the server was the addition of `ADVERTISEMENT.setNintendoLimited(true);`

**Comment by ambiennt** [comment]
Even after removing this line, I still get stuck on "Locating Server"

Tested with
https://github.com/Kazzuk/ProxyPass/suites/8568765691/artifacts/383241432
