### ISSUE TITLE
ItemStackRequest packet PacketSerializeException with 1.19.40

### ISSUE THREAD

**Issue by onebeastchris** [NukkitX/ProxyPass#39]
https://paste.gg/p/anonymous/af29a6399b31405a850ba5ca0678204f
Using 1.19.40 server + client to look at the packets sent during right-click quick crafting results in this error - i'm unable to see the ItemStackRequest packet
It doesnt appear to happen if one clicks the recipe, and then crafts it, but right-click quick crafting produces it
ty!

**Comment by SupremeMortal** [comment]
This was fixed in https://github.com/CloudburstMC/Protocol/commit/dddb57c1f61d7c230e4ec0f3b4ce28e872665bd0 , however I assume you are using the prebuilt binaries, so I've just re-run the last build.

**Comment by onebeastchris** [comment]
ah, that's likely it
tysm!
