### ISSUE TITLE
Version 1.19.51 can not be linked into the game

### ISSUE THREAD

**Issue by violets007** [NukkitX/ProxyPass#40]
![mnggiflab-compressed-out](https://user-images.githubusercontent.com/20490066/214351918-a5c2fdd4-f1cd-4a21-af70-19608dc71a7b.gif)

- ### Log
[latest.log](https://github.com/CloudburstMC/ProxyPass/files/10492058/latest.log)

- ### proxypass config
<img width="818" alt="image" src="https://user-images.githubusercontent.com/20490066/214364992-87b03614-6a0b-44f7-b89b-1a9d07bcea52.png">

- ### Server Connection Information
<img width="625" alt="image" src="https://user-images.githubusercontent.com/20490066/214366665-b442e70d-1a56-4ad1-a8bb-efd6d08fdbfb.png">

**Comment by Kazzuk** [comment]
Ensure both the proxy bind and destination address are set to `127.0.0.1` and connect to this address. Also, verify that loopback is enabled. If not, run the below command and restart your client.
```bash
# Run the loopback exemption command in powershell as admin
CheckNetIsolation LoopbackExempt -a -n="Microsoft.MinecraftUWP_8wekyb3d8bbwe"
```
